### ISSUE TITLE
Usage of filter for view brakes it

### ISSUE THREAD

**Issue by Pikealot** [Gladior-B-V/linkedin-company-connector#1]
Hi,
I want to display the followers of my company account and filter it by industry. As soon as I add the filter to the diagram data, data studio throws the "error within the configuration of the data pool". Error-id f41d4028.
Can I change anything on my end to resolve that?
Thanks,
Holger

**Comment by zoedufrenne** [comment]
Hi Holger,
I'm sorry that we didn't respond sooner. but the issue has been resolved. You can now use industry as a dropdown filter in your dashboard. 

Please let me know, if there is anything else. 
Zoé du Frenne
