### ISSUE TITLE
Indeed sponsored jobs issue

### ISSUE THREAD

**Issue by theoneinred** [Gladior-B-V/linkedin-company-connector#10]
Deze vraag gaat eigenlijk niet over de linkedin company connector maar over de Indeed Sponsored Jobs connector.
Aangezien ik geen repository hiervan zie, zet ik het voor nu even hierin.
Het probleem wat ik nu ervaar is dat in Looker Studio de data niet correct staat weergegeven.
Als ik inlog op Indeed Analytics hebben we maar liefst 100 sollicitaties gehad, maar in Looker worden er maar 6 aangegeven via jullie connector.
Wat gaat hier mis?

Hulp wordt zeer op prijs gesteld!

**Comment by zoedufrenne** [comment]
@theoneinred We hebben hier wel een repository van: https://github.com/Gladior-B-V/indeed-connector/issues, maar via hier kan het ook! Kan je met mij service@gladior.com het dashboard delen? Dan ik even meekijken! Of anders wat screenshots, maar dan ook de instellingen er bij :)

**Comment by theoneinred** [comment]
Hi Zoë, dankjewel voor de reply! En dank voor het delen van de repo. Maar
het schijnt alweer te werken : )
Ik denk dat het eenmalig was. Mocht ik toch weer iets geks zien, dan laat
ik het direct weten. Fijne dag!

Vrgr, Redouan

Op ma 2 dec 2024 om 08:27 schreef zoegerritsen ***@***.***>:

**Comment by zoedufrenne** [comment]
Hi Redouan, Gelukkig, goed om te lezen. Fijne dag!

**Comment by theoneinred** [comment]
Hi Zoe, even geleden weer!
Vraagje, verzoekje eigenlijk, zouden jullie ook voor Werkzoeken.nl een
connector kunnen maken?
Dit platform is steeds groter aan het worden en graag zou ik via Looker
Studio hier een koppeling meer willen maken.
De API doc is te vinden via https://www.werkzoeken.nl/doc/

Hoor 't graag, thanks alvast!

Op ma 2 dec 2024 om 10:37 schreef zoegerritsen ***@***.***>:

**Comment by zoedufrenne** [comment]
Hi @theoneinred, dat is heel toevallig. Wij hebben zijn inderdaad bezig met ontwikkeling van verschillende jobboards, werkzoeken.nl staat ook zeker in dit lijstje. In eerste instantie zal dit voor ons ATS systeem gaan werken, maar als uitbreiding hierop is het waarschijnlijk ook mogelijk als connector. Als wij hier een update over hebben, laat ik je dit weten.

**Comment by theoneinred** [comment]
Hi Zoë, dank voor je bericht. Leuk te horen dat jullie bezig zijn met de
ontwikkeling hiervan. En mocht je gaandeweg nog een update hebben, dan hoor
ik dat uiteraard graag. Wordt gewaardeerd, thanks!

Op ma 26 mei 2025 om 14:25 schreef zoegerritsen ***@***.***>:
