### ISSUE TITLE
Error with data (comments, likes, reactions)

### ISSUE THREAD

**Issue by seekerparkingdev** [Gladior-B-V/linkedin-company-connector#2]
Hi! look at this,

The linkedin connector, no matter if it is a youtube link, a PDF, an image, likes, reactions and comments, catalogs them as Null.

https://drive.google.com/drive/folders/1Hh8kdJHZmEo8bLORW0Sl2aWPVg-WLuSl?usp=sharing

**Comment by zoedufrenne** [comment]
Hi @seekerparkingdev 
the connector supports only the posts posted with 1 photo. The other forms are not defaulted by the API we use. Here is explained exactly what the field is all about: https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin

shareMediaCategory = Represents the media assets attached to the share. Possible values include: 

- NONE - The share does not contain any media, and will only consist of text.
- ARTICLE - The share contains a URL.
- IMAGE - The Share contains an image.
