### ISSUE TITLE
LinkedIn company connector does not work

### ISSUE THREAD

**Issue by Ecocompteur** [Gladior-B-V/linkedin-company-connector#3]
Hi, I would like to connect LinkedIn to Looker Studio. However I am blocked at the connect with Linkedin step.
Can you please tell me how I can solve this ? 
Here are the screenshots :
![LOOKER](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/1a2ca75a-3ac3-43a6-a03a-b0725cd34a36)
When I click on "Authorize", it asks me to sign in to LinkedIn :
![SIGN](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/1d3b6d9f-c8c6-4f45-9b6a-9383593d77ed)
I then click, type my password and then this happens :
![BUG](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/9db23e89-f6d3-4bda-b72c-83a32165c74f)
And it keeps spinning and nothing happens.
Can you help me solve this ? 
Many thanks,

**Comment by zoedufrenne** [comment]
Hi @Ecocompteur we've updated the connector and the error should not occur anymore. Can you test this?

**Comment by Ecocompteur** [comment]
Hi Zoe,

Thanks for your help unfortunately, it generates an error :
***@***.***
Many thanks,

Tristan Le Cozannet

De : zoegerritsen ***@***.***>
Envoyé : jeudi 18 janvier 2024 09:29
À : Gladior-B-V/linkedin-company-connector ***@***.***>
Cc : Tristan Le Cozannet ***@***.***>; Mention ***@***.***>
Objet : Re: [Gladior-B-V/linkedin-company-connector] LinkedIn company connector does not work (Issue #3)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Hi @Ecocompteur<https://github.com/Ecocompteur> we've updated the connector and the error should not occur anymore. Can you test this?

**Comment by zoedufrenne** [comment]
Hi @Ecocompteur what kind of error do you  get? Is when you connect a new credential to the Data hub app? or is it in Looker Studio?

**Comment by Ecocompteur** [comment]
Here are the different steps :

1 : ***@***.***
2: ***@***.***
3: ***@***.***
4 : ***@***.***

Does this help ?

Thanks,

Tristan Le Cozannet


De : zoegerritsen ***@***.***>
Envoyé : jeudi 18 janvier 2024 11:09
À : Gladior-B-V/linkedin-company-connector ***@***.***>
Cc : Tristan Le Cozannet ***@***.***>; Mention ***@***.***>
Objet : Re: [Gladior-B-V/linkedin-company-connector] LinkedIn company connector does not work (Issue #3)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Hi @Ecocompteur<https://github.com/Ecocompteur> what kind of error do you get? Is when you connect a new credential to the Data hub app? or is it in Looker Studio?

**Comment by zoedufrenne** [comment]
Hi @Ecocompteur I only see this:
![image](https://github.com/Gladior-B-V/linkedin-company-connector/assets/84766152/8b39f33f-622a-443a-b4ca-85aba56c769a)

I can't reconize any bugs with only ***

**Comment by Ecocompteur** [comment]
Is it better with linked files ?


Tristan Le Cozannet


De : zoegerritsen ***@***.***>
Envoyé : jeudi 18 janvier 2024 13:47
À : Gladior-B-V/linkedin-company-connector ***@***.***>
Cc : Tristan Le Cozannet ***@***.***>; Mention ***@***.***>
Objet : Re: [Gladior-B-V/linkedin-company-connector] LinkedIn company connector does not work (Issue #3)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Hi @Ecocompteur<https://github.com/Ecocompteur> I only see this:
image.png (view on web)<https://github.com/Gladior-B-V/linkedin-company-connector/assets/84766152/8b39f33f-622a-443a-b4ca-85aba56c769a>

I can't reconize any with only ***

**Comment by zoedufrenne** [comment]
I can only see the screenshots you've attached in your first message, in the other message I don't see any screenshots.

**Comment by Ecocompteur** [comment]
Hello,

Do you have any other way I could send you these screenshots ?

Many thanks,

Tristan Le Cozannet


De : zoegerritsen ***@***.***>
Envoyé : jeudi 18 janvier 2024 15:03
À : Gladior-B-V/linkedin-company-connector ***@***.***>
Cc : Tristan Le Cozannet ***@***.***>; Mention ***@***.***>
Objet : Re: [Gladior-B-V/linkedin-company-connector] LinkedIn company connector does not work (Issue #3)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

I can only see the screenshots you've attached in your first message, in the other message I don't see any screenshots.

**Comment by zoedufrenne** [comment]
@Ecocompteur Can you do it the same way as you did in your first message? Those screenshot are visible.

**Comment by Ecocompteur** [comment]
![1](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/d9fc1233-2064-42bb-a606-3c4d8d4876c7)
![2](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/47942c63-2816-4b9a-8753-bccf97b5d724)
![3](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/4036e8b0-7ecf-44b0-8282-026559ee702d)
![4](https://github.com/Gladior-B-V/linkedin-company-connector/assets/155961600/26011307-e3c6-43ca-bc11-637a1f295297)

Is this better ?

**Comment by zoedufrenne** [comment]
@Ecocompteur yes these are visible, can you in the overview of the second screenshot click on the three dots of our connector and revoke acces? and then try to make a new connection?

**Comment by Ecocompteur** [comment]
Hello, it did not work ;)

**Comment by zoedufrenne** [comment]
Hi @Ecocompteur can you share your data hub id? Development will check if the can find the reason, why it isn't working for you. At our side the connector is working, so we can't recreate the issue. 

Data Hub ID you can find to click on edit your profile and the long code on the bottom of the pop up is your Data Hub ID.
