### ISSUE TITLE
The created dimension error

### ISSUE THREAD

**Issue by davidzeng28** [Gladior-B-V/linkedin-company-connector#4]
Dear, I have recently found an error and hope you can enlighten me with this, I have tried to use multiple ways to modify visitors by job function and it didn't work, may I ask is it because of the restriction of the API?
Thanks

**Comment by davidzeng28** [comment]
FYI：The connector is Linkedin Company.
Also, I cannot organize visitors or total page views on time

**Comment by davidzeng28** [comment]
FYI the connector is linkedin company connector

**Comment by davidzeng28** [comment]
FYI the connector is linkedin company connector
Also, total views on page cannot be viewed based on date filter

**Comment by davidzeng28** [comment]
Dear, I have recently found an error and hope you can enlighten me with this, I have tried to use multiple ways to modify visitors by job function and it didn't work, may I ask is it because of the restriction of the API?
Thanks

**Comment by zoedufrenne** [comment]
I'll close this one, because it's the same as: https://github.com/Gladior-B-V/linkedin-company-connector/issues/5
