### ISSUE TITLE
Visitors by job function and industry

### ISSUE THREAD

**Issue by davidzeng28** [Gladior-B-V/linkedin-company-connector#5]
Dear, I have recently found an error and hope you can enlighten me with this, I have tried to use multiple ways to modify visitors by job function and it didn't work, may I ask is it because of the restriction of the API? Thanks

**Comment by davidzeng28** [comment]
<img width="383" alt="Screen Shot 2024-02-19 at 5 11 33 PM" src="https://github.com/Gladior-B-V/linkedin-company-connector/assets/113512635/502202be-51ea-4ba3-8509-2fa8b02c1c04">
dimension is Job function, it worked several days ago but today it failed and I have tried to change the timeline it also didnt work
THank you
@zoedufrenne

**Comment by davidzeng28** [comment]
Hi @zoedufrenne 
FYI: when put this metrics on scorecard this is the error

Community Connector Error
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

Error ID: 8ea40379

**Comment by davidzeng28** [comment]
@zoedufrenne can you help me with this, thank you

**Comment by zoedufrenne** [comment]
Hi @davidzeng28 we've tested the same widget, but on our end, it still works. (same with the other endpoints under demographics, industry; location; company size; seniority). See screenshot:
![image](https://github.com/Gladior-B-V/linkedin-company-connector/assets/84766152/fadc43f8-4974-4c5b-9243-1c9f46da7a04)

Unfortunately, we can't recreate the issue for you. If you want us to look to your case specific we can set up an hour support (€115,-) to check your dashboard and why it isn't working for you.
