### ISSUE TITLE
Engagement rate not updating

### ISSUE THREAD

**Issue by rylanczuczman** [Gladior-B-V/linkedin-company-connector#6]
Hello there,

Firstly thank you for such a great connector, it's working brilliantly apart from this one issue that I'm facing.

I have the connector pulling data from our company page into Looker Studio, and I have a set of headline KPIs set up as scorecards, one of which is engagement rate. When I set this to average and try to determine a date range, it always returns the same figure of 6.44%, no matter what the date is. 

Is this something you're aware of, and is there a fix for this please?

Cheers,
Rylan

Tagging for visbility @zoedufrenne

**Comment by zoedufrenne** [comment]
@rylanczuczman thanks for your message. This is not something we are aware of. I checked our own dashboards and I see the same issue. I'll let development know and keep you posted!

**Comment by rylanczuczman** [comment]
Thank you!

**Comment by zoedufrenne** [comment]
Hi @rylanczuczman we've made an update to the LinkedIn connector. The engagement rate is changing at our side. Can you update the connector and test it?

**Comment by rylanczuczman** [comment]
That's working now, thank you @zoedufrenne!
