### ISSUE TITLE
Data Are Not Accurate

### ISSUE THREAD

**Issue by hersheypizza** [Gladior-B-V/linkedin-company-connector#8]
We are facing some issues with the LinkedIn Company Connector. The data the connector is pulling is not accurate on the LinkedIn dashboard analytics. For example, on the backend, we have 9,419 Impressions, but the pulled data is only 9,012. This is for all the metrics besides the Total Followers, which is fine. The date filter we have set up matched, and the data aggregation is in SUM, so we are not sure why the data are not accurate and equal.

Is there anything we should do to fix this? Thank you so much! We'll appreciate your help on this~

**Comment by rylanczuczman** [comment]
Hey guys, I'm also seeing inconsistencies with data:

For our graphs they seem to be pulling monthly figures ok, but the scorecards show different figures when I filter by the same month. Could someone take a look into this please?

**Comment by rkooiker** [comment]
Hi @rylanczuczman could you share a dashboard were this issue occurs, so that we can look further into the issue? You can share it with service@gladior.com

**Comment by rkooiker** [comment]
@hersheypizza could you share some screenshots of the dashboard, and the linkedin analytics page?

**Comment by rkooiker** [comment]
Hi @rylanczuczman and @hersheypizza, I have found the cause of this problem. Currently, our connector is only able to retrieve data from the last x number of posts. If this is not enough for your data needs we might be able to help you, though it will require a custom solution. You can contact us at service@gladior.com to discuss what paid options we have available.
