### ISSUE TITLE
"Unknown Error - There's an error communicating with the service"

### ISSUE THREAD

**Issue by cognosceteipsum1** [Gladior-B-V/linkedin-company-connector#9]
Hello,
I've encountered an issue with the connector in Looker Studio. Since two days ago, I've been receiving the following error message: "Unknown Error - There's an error communicating with the service."
I've tried logging out and back in both Looker Studio and LinkedIn, but it hasn't resolved the problem. I haven't made any changes on my end before this issue started.
Is anyone else experiencing the same issue? Any assistance would be greatly appreciated.
Thank you!

**Comment by rkooiker** [comment]
Hi @cognosceteipsum1,

Could you share your Data Hub user id? Then we can look further into the issue. you can find it under your profile -> Edit profile. It's the greyed out number at the bottom.

**Comment by cognosceteipsum1** [comment]
ff00bab1-7493-4bd1-8f92-536fb8747619

Thanks for looking into this!

**Comment by rkooiker** [comment]
Can you try to refresh your credential? You can do this by going to datahubapp.gladior.com, and going through the steps to create a data source again. If you need any help, please let me know.

**Comment by cognosceteipsum1** [comment]
Did it, now it works again perfectly, many many thanks for your help!
